# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import localflavor.us.models
import locations.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('phone', localflavor.us.models.PhoneNumberField(blank=True, help_text=b'Format: XXX-XXX-XXXX', max_length=20)),
                ('photo', filebrowser.fields.FileBrowseField(blank=True, help_text=b'Valid file formats: .jpg, .png', max_length=200, null=True, verbose_name=b'Photo')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, help_text=b'Valid file formats: .jpg, .png', max_length=200, null=True, verbose_name=b'Image')),
                ('bio', models.TextField(help_text=b'A short biography for the artist')),
                ('website', models.URLField(blank=True, help_text=b'The artists website')),
                ('location', locations.fields.LocationField(blank=True, help_text=b'The artists current location during the festival', max_length=255, verbose_name=b'current location')),
                ('status', models.IntegerField(choices=[(1, b'Live'), (2, b'Draft'), (3, b'Hidden')], default=1, help_text=b'Only entries with live status will be publicly displayed.')),
                ('featured_home', models.BooleanField(verbose_name=b'featured on Home page')),
                ('featured_artists', models.BooleanField(verbose_name=b'featured on Artists page')),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from name. Must be unique.', unique=True)),
                ('user', models.OneToOneField(blank=True, help_text=b'Create a user account for the artist.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'status', 'featured_home', 'featured_artists'],
            },
        ),
    ]
