# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fields
import filebrowser.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_type', models.CharField(choices=[(b'person', b'Person'), (b'entity', b'Entity')], max_length=30)),
                ('name', models.CharField(help_text=b'If the affiliate is a person,\n                                       enter his or her name in the \n                                       format: firstname lastname', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('image', filebrowser.fields.FileBrowseField(blank=True, help_text=b'Valid file formats: .jpg, .png', max_length=200, null=True, verbose_name=b'Image')),
                ('featured_home', models.BooleanField(verbose_name=b'featured on Home page')),
                ('featured_affiliates', models.BooleanField(verbose_name=b'featured on Affiliates page')),
                ('slug', models.SlugField(help_text=b'Unique web title automatically \n                                         generated from name.', unique=True)),
                ('first_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('last_name', models.CharField(blank=True, editable=False, max_length=255)),
            ],
            options={
                'ordering': ['affiliate_level', 'affiliate_type', 'last_name', 'first_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', fields.PositionField(blank=True)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='affiliate',
            name='affiliate_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliates.AffiliateLevel'),
        ),
    ]
