# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields
import localflavor.us.models
import locations.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('aio', models.BooleanField()),
                ('host', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('location', locations.fields.LocationField(blank=True, max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name=b'contact person')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', localflavor.us.models.PhoneNumberField(blank=True, help_text=b'Format: XXX-XXX-XXXX', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('image', filebrowser.fields.FileBrowseField(blank=True, help_text=b'Valid file formats: .jpg, .png', max_length=200, null=True, verbose_name=b'Image')),
                ('slug', models.SlugField(help_text=b'Suggested value automatically \n                                         generated from name. Must be unique per published date.', unique_for_date=b'start_date')),
                ('featured_home', models.BooleanField(verbose_name=b'featured on Home page')),
                ('featured_events', models.BooleanField(verbose_name=b'featured on Events page')),
                ('affiliate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='affiliates.Affiliate')),
            ],
        ),
    ]
